
<section id="login-container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2" id="login-wrapper">
		<?php echo (isset($this->alert) ? $this->alert : ''); ?>
			<div class="panel panel-success animated flipInY">
				<div class="panel-heading">
					<h3 class="panel-title text-center">     
						Cadastro de Usuario
					</h3>      
				</div>
				<div class="panel-body">
					<div class="form-group col-md-12 col-xs-12 col-sm-12 col-lg-12">
						<div class="col-md-4">
							<h4 class="active">* Campos Obrigatorios</h4>
							<div id="errors_campus"></div>
						</div>
						<div class="col-md-offset-4 col-md-4">
							<div class="row"><b>Logar com:</b></div>
							<div id="api_google" class="row g-signin2" data-onsuccess="onSignIn"></div>
							<a href="#" class="row g-signin1" onclick="signOut();">Sair do Google</a>

						</div>
						<div class="row col-md-offset-5 col-md-4"><span class="label label-primary">-----OU-----</span></div>
					</div>
					
					<form method="post" class="form-horizontal" action="<?=BASE?>usuario/cadastroDemandante/" role="form">
						<div class="form-group"></div>
						<div class="form-group has-feedback">
							<div id="valida_nome" class="col-md-4 ">
								<label class="control-label" for="username">Nome: *</label>
								<input type="text" required="required" class="form-control" id="id_nome" name="nome" value="<?=$view_request['nome'];?>" placeholder="Nome Completo" onblur="validaNome(this.value);" />
								<span id="valida_nome_icon" class='form-control-feedback' aria-hidden='true'></span>


							</div>
							<div id="valida_sobre" class="col-md-8">
								<label class="control-label" for="username">Sobrenome: *</label>
								<input value="<?=$view_request['sobrenome'];?>" type="text" required="required" class="form-control" id="id_Sobrenome" name="sobrenome" onblur="validaSobre(this.value);" placeholder="Nome Completo"/>
								<span id="valida_sobre_icon" class='form-control-feedback' aria-hidden='true'></span>
							</div>
						</div>
						<div id="dados_logon" class="form-group has-feedback">
							<div id="valida_usu" class="col-md-3">
								<label for="username">Usuario: *</label>
								<input value="<?=$view_request['usuario'];?>" type="text" class="form-control" id="id_usuario" name="usuario" placeholder="Usuário" onblur="validaUsu(this.value);" />
								<span id="valida_usu_icon" class='form-control-feedback' aria-hidden='true'></span>	
							</div>
							<div id="valida_senha" class="col-md-3">
								<label for="password">Senha: *</label>
								<input value="<?=$view_request['senha'];?>" type="password"  class="form-control" id="senha" name="senha" placeholder="Senha" onblur="validaSenha(this.value);"/>
								<span id="valida_senha_icon" class='form-control-feedback' aria-hidden='true'></span>
							</div>
							<div id="valida_confirmar-senha" class="col-md-3">
								<label for="password">Confirmar Senha:</label>
								<input value="<?=$view_request['salt'];?>" type="password"  class="form-control col-md-5" id="confirsenha" name="salt" placeholder="Senha" onkeydown="validarSenha();" />
								<span id="valida_confirmar-senha_icon" class='form-control-feedback' aria-hidden='true'></span>
							</div>

						</div>
						<div class="form-group">

						</div>
						<div class="form-group">
							<div id="valida_email" class="col-md-12">
								<label for="exampleInputEmail1">Email: *</label>
								<input value="<?=$view_request['email_id'];?>" type="email" class="form-control" id="id_email" name="email_id" placeholder="Email"/>
								
							</div>
						</div>
						<div class="form-group ">
							<div class="col-md-4">
								<label>Estado: *</label>
								<select value="<?=$view_request['estado_id'];?>" name="estado_id" class="form-control">
									<?php   foreach($view_estados as $es){ ?>

									<option value="<?=$es->id;?>"><?=$es->sigla;?></option>
									<?php } ?>
								</select>
							</div>
							<div id="valida_telefone" class="col-md-4">
								<label for="password">Telefone: *</label>
								<input value="<?=$view_request['telefone'];?>" type="text" required="required" placeholder="(DD)9 9999-9999" class="form-control col-md-5" id="telefone_id" name="telefone" placeholder="Senha" onblur="validaTelefone(this.value);" />
								<span id="valida_telefone_icon" class='form-control-feedback' aria-hidden='true'></span>
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-3 col-md-offset-2">
								<button id="btn_cad" onclick="validaNome();" disabled="disabled" class="btn btn-success">Cadastrar</button>
							</div>
							<div class="col-md-3 col-md-offset-3">
								<a href="<?=BASE?>" type="submit" class="btn btn-danger">Voltar</a>
							</div>
						</div>

					</form>
					
					<div class="progress">
						<div id="progress-b" class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em;width: 0%;">
							0%
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row col-md-6 col-md-offset-3">
		<form action="<?=BASE?>usuario/solicitarChave/" method="post">
			<label for="email_institucional">Para Pesquisador/Extensionista, Solicite aqui seu cadastro!</label>
			<div class="input-group">
				<div class="input-group-btn">
				<button class="btn btn-success"">Enviar</button>
				</div>
				<input id="email_institucional" type="text" name="email" class="form-control" placeholder="Email Institucional" aria-describedby="basic-addon2" required="required">
				<span class="input-group-addon" id="basic-addon2">@ifto.edu.br</span>

			</div>
		</form>
	</div>
	<div id="reload"><?=$view_reload;?></div>
</section>
