<section id="login-container">
	<?php echo (isset($this->alert) ? $this->alert : ''); ?>
	<div class="row col-md-6 col-md-offset-3">
		<form action="<?=BASE?>usuario/solicitarChave/" method="post">
			<label for="email_institucional">Para Pesquisador/Extensionista, Solicite aqui seu cadastro!</label>
			<div class="input-group">
				<div class="input-group-btn">
				<button class="btn btn-success"">Enviar</button>
				</div>
				<input id="email_institucional" type="text" name="email" class="form-control" placeholder="Email Institucional" aria-describedby="basic-addon2" required="required">
				<span class="input-group-addon" id="basic-addon2">@ifto.edu.br</span>

			</div>
		</form>
	</div>
</section>