<div id="popup-log" class=" col-md-4 col-md-offset-4">
	<?php echo (isset($this->alert) ? $this->alert : ''); ?>
    <div class="panel panel-success animated flipInY ">
      <div class="panel-heading">
        <h3 class="panel-title text-center">
        Recuperação de Senha
        </h3>
      </div>
    <div class="panel-body">
    		<form action="<?=BASE?>recuperarsenha/solicitar/" method="post" class="form-horizontal" role="form">
		      <div class="form-group">
		        <div class="col-md-12">
		          <label for="usuario">E-mail</label>
		            <input type="email" required="required" name="email" placeholder="E-mail..." class="form-control">
		        </div>
		      </div>
		     
		          <button class="btn btn-default">Enviar link de redefinição</button>
		    </form>
		</div>
	</div>
</div>