
</div>
	</div>
	<div class="container-fluid colorFooter">
		<div class="row footer_org">
			<div class="col-md-4 col-md-offset-4 text-center footer">
				NEEDS  <?=date("Y");?> &copy; - Todos os direitos reservados
			</div>
			<div class="col-md-offset-2 col-md-2 butons_footer">
				<a href="" class="">Contatos</a>
				<br>
				<a href="" class="">Sobre Nós</a>
			</div>
		</div>
	</div>
</body>
</html>