<!doctype html>
<html lang="pt-br">
<head>
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
	<!--<meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="1009135910247-k8693mh4cljccnju8nd2q21lpn3mu5i0.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
     Do GOOOGLE acima -->
	<meta charset="utf-8">
	<meta name="author" content="Bruno C. Santos">
	<meta name="generator" content="HXPHP Framework v1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?=$view_title;?></title>
	<link rel="shortcut icon" href="<?=IMG;?>favicon.ico" type="image/x-icon">
	
	<link rel="stylesheet" href="<?=CSS;?>bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>font-awesome.min.css" type="text/css">
	<?=$add_css;?>
	<link rel="stylesheet" href="<?=CSS;?>style.css" type="text/css">
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="<?=JS;?>bootstrap.min.js"></script>
	<?=$add_js;?>
	<script type="text/javascript" src="<?=JS;?>main.js"></script>
</head>
<body>
	<div class="full bg color" id="header">
		<div class="row">
			<div class="container">
				<div class="col-md-12">
					
				</div>
			</div>
		</div>	
	</div>

	<?=$view_message;?>

	<div class="container">
			<div class="col-md-12">