<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Vinnicyus Carvalho	">
	<meta name="generator" content="DemandaAi">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $view_title; ?></title>
	<link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
	<?php 
		echo $add_css;
		echo $add_js;
	?>
</head>
<body>
	<div class="container">