<!doctype html>
<html lang="pt-br">
<head>
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
	<!--<meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="1009135910247-k8693mh4cljccnju8nd2q21lpn3mu5i0.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
     Do GOOOGLE acima -->
	<meta charset="utf-8">
	<meta name="author" content="Vinnicyus Carvalho ">
	<meta name="generator" content="DemandaAi 1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
	<title><?=$view_title;?></title>
	<?=$add_css;?>
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
	<?=$add_js;?>
</head>
<body>
	<div class="full bg color" id="header">
		<div class="row">
			<div class="container">
				<div class="col-md-12">
					
				</div>
			</div>
		</div>	
	</div>

	<div class="container">
			<div class="col-md-12">