<section id="login-container">
    <div class="row">
        <div id="popup-log" class="popup-logon col-md-3 col-md-offset-4">
            <div class="panel panel-success animated flipInY ">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">
                        Logon
                    </h3>
                </div>
                <div class="panel-body">
                    <form action="<?=SITE?>login/logar/" method="POST" class="form-horizontal" role="form">
                        <div class="form-group">
                            <div class="col-md-12">
                                <label for="usuario">Login</label>
                                <input type="text" required="required" name="usuario" placeholder="Usuário..." class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <label for="senha">Password</label>
                                <input type="password" id="senha" name="senha" placeholder="Senha" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-success">Logar</button>
                            </div>
                            <div class="col-md-3 col-md-offset-4">
                                <button type="button" onclick="hiddenLogin();" class="btn btn-danger">Fechar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</section>
