<section id="search-container">
	<div class="row">
		<div class="col-md-6">
		
			<?php foreach ($view_search as $key => $value) {
				echo $value;	
			}?>
		</div>
		<form action="<?=$view_endereco;?>" method="get" role="search">
			<div class="col-md-5 col-md-offset-1">
				<div class="input-group">
					<input type="text" class="form-control" name="search" placeholder="Qual a sua Dor?" value="<?=$view_pesquisa?>"/>
					<span class="input-group-btn">
						<button id=" btn-danger-logon" class="btn btn-success"><i class="fa fa-search"></i></button>
					</span>
				</div>
			</form>
			<span class="label label-success col-md-6">Pesquisa: <?=$view_pesquisa?></span><span class="col-md-4 col-md-offset-2 label label-default">Ocorrencias: <?=$view_ocorrencias?></span>
			<div class="row">
			<div id="popup-log" class="popup-l col-md-8 col-md-offset-4">
					<div class="panel panel-success animated flipInY ">
						<div class="panel-heading">
							<h3 class="panel-title text-center">
								Logon
							</h3>
						</div>
						<div class="panel-body">
							<form action="<?=SITE?>login/logar/" method="POST" class="form-horizontal" role="form">
								<input type="text" value="<?=$view_pesquisa?>" name="pesquisa" style="display: none;"/> 
								<div class="form-group">
									<div class="col-md-12">
										<label for="usuario">Login</label>
										<input type="text" required="required" name="usuario" placeholder="Usuário..." class="form-control">
									</div>
								</div>
								<div class="form-group">
									<div class="col-md-12">
										<label for="senha">Password</label>
										<input type="password" id="senha" name="senha" placeholder="Senha" class="form-control">
									</div>
								</div>
								<div class="form-group">
									<div class="col-md-3">
										<button class="btn btn-success">Logar</button>
									</div>
									<div class="col-md-3 col-md-offset-4">
										<button type="button" onclick="hiddenLogin();" class="btn btn-danger">Fechar</button>
									</div>
								</div>
								<div class="form-group">
									<div class="g-signin2 col-md-7" data-onsuccess="onSignIn"></div>
									
										<a class="btn btn-success" href="<?=SITE?>register/">Cadastre-se</a>
									
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</section>

